name: build-image

# 👇  NEW: let the workflow write to the repo
permissions:
  contents: write

on:
  schedule:
    - cron: '17 * * * *'
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.x'}
      - run: pip install -r requirements.txt
      - run: python render.py
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'out.png --force'
          message: 'auto: refresh image'
